// GENERATED by scripts/build-tokens-dart.mjs from tokens/vela.tokens.json — do not edit.
// @omkarux/vela 0.9.0. Edit the JSON and run `npm run tokens`: tokens.css, the Figma
// library and this file are all compiled from the same source.
//
// Bind semantics ([VelaColors]) in widgets. Primitives exist only to be aliased — the same
// rule the CSS and the Figma library follow. Sizes are logical pixels, 1:1 with the CSS px.

import 'package:flutter/material.dart';

/// Primitive palette. Do not use directly in widgets — bind a semantic from [VelaColors].
abstract final class VelaPrimitives {
  static const Color black = Color(0xFF191D1F);
  static const Color white = Color(0xFFFFFFFF);
  static const Color grey50 = Color(0xFFF7F9F9);
  static const Color grey100 = Color(0xFFEEF2F2);
  static const Color grey200 = Color(0xFFDDE3E4);
  static const Color grey300 = Color(0xFFC8D0D2);
  static const Color grey400 = Color(0xFFA3AEB1);
  static const Color grey500 = Color(0xFF7F8C90);
  static const Color grey600 = Color(0xFF667377);
  static const Color grey700 = Color(0xFF49555A);
  static const Color grey800 = Color(0xFF333D41);
  static const Color grey850 = Color(0xFF262E31);
  static const Color grey900 = Color(0xFF1B2225);
  static const Color grey950 = Color(0xFF11171A);
  static const Color primary300 = Color(0xFF5FB8C9);
  static const Color primary400 = Color(0xFF2F9DB3);
  static const Color primary500 = Color(0xFF0A6C7D);
  static const Color primary600 = Color(0xFF075462);
  static const Color blue100 = Color(0xFFE6EEFB);
  static const Color blue150 = Color(0xFFCFDFF7);
  static const Color blue300 = Color(0xFF85AAE8);
  static const Color blue500 = Color(0xFF3D7FD6);
  static const Color blue700 = Color(0xFF35558A);
  static const Color blue950 = Color(0xFF0E1A2E);
  static const Color red100 = Color(0xFFFCE8E6);
  static const Color red300 = Color(0xFFF0918C);
  static const Color red500 = Color(0xFFDD4B3E);
  static const Color red700 = Color(0xFFAB3125);
  static const Color red950 = Color(0xFF2A1310);
  static const Color critical100 = Color(0xFFF2D6D4);
  static const Color critical300 = Color(0xFFCC6F68);
  static const Color critical500 = Color(0xFFA81C14);
  static const Color critical700 = Color(0xFF7D150F);
  static const Color critical950 = Color(0xFF2B100E);
  static const Color yellow100 = Color(0xFFFDF1D3);
  static const Color yellow300 = Color(0xFFF7D382);
  static const Color yellow500 = Color(0xFFF0C14E);
  static const Color yellow600 = Color(0xFFC99A10);
  static const Color yellow700 = Color(0xFF9A7A0C);
  static const Color yellow800 = Color(0xFF7A6224);
  static const Color yellow950 = Color(0xFF26200E);
  static const Color orange100 = Color(0xFFFDE7D0);
  static const Color orange300 = Color(0xFFF5AD63);
  static const Color orange500 = Color(0xFFEA7F1A);
  static const Color orange600 = Color(0xFFC86A0D);
  static const Color orange700 = Color(0xFF9C5408);
  static const Color orange950 = Color(0xFF281A0B);
  static const Color green100 = Color(0xFFDCEFE0);
  static const Color green300 = Color(0xFF86C795);
  static const Color green500 = Color(0xFF4AA863);
  static const Color green700 = Color(0xFF1F7340);
  static const Color green800 = Color(0xFF175C33);
  static const Color green950 = Color(0xFF0D2318);
}

/// Semantic colours — one field per token, with the light and dark values the CSS ships.
///
/// Read with `Theme.of(context).extension<VelaColors>()!`, or use [VelaColors.light] and
/// [VelaColors.dark] directly. [velaThemeData] installs the right one for a [Brightness].
@immutable
class VelaColors extends ThemeExtension<VelaColors> {
  const VelaColors({
    required this.bgGlobal,
    required this.bgContainer,
    required this.bgRaised,
    required this.bgHover,
    required this.bgTooltip,
    required this.bgInactive,
    required this.bgSelected,
    required this.primaryTint,
    required this.primaryActiveBg,
    required this.borderDefault,
    required this.borderSubtle,
    required this.borderActive,
    required this.borderInactive,
    required this.borderAction,
    required this.textDefault,
    required this.textHeading,
    required this.textDeEmphasized,
    required this.textInactive,
    required this.textLink,
    required this.textOnBrand,
    required this.textOnTint,
    required this.textError,
    required this.iconDefault,
    required this.iconStrong,
    required this.iconSelected,
    required this.iconDisabled,
    required this.iconOnBrand,
    required this.btnPrimaryBg,
    required this.btnPrimaryHoverBg,
    required this.btnPrimaryBorder,
    required this.btnPrimaryText,
    required this.btnStandardBg,
    required this.btnStandardHoverBg,
    required this.btnStandardText,
    required this.btnHollowPrimaryText,
    required this.btnHollowPrimaryBorder,
    required this.btnDisabledBg,
    required this.btnDisabledText,
    required this.btnDestructiveBg,
    required this.btnDestructiveHoverBg,
    required this.btnDestructiveText,
    required this.btnDestructiveHollowText,
    required this.btnStandardBorder,
    required this.btnHollowHoverBg,
    required this.controlBg,
    required this.controlBorder,
    required this.controlBorderHover,
    required this.controlBorderActive,
    required this.controlBorderError,
    required this.controlBgDisabled,
    required this.controlPlaceholder,
    required this.toggleOffBg,
    required this.toggleOnBg,
    required this.toggleKnob,
    required this.bgSeveritySuccess,
    required this.borderSeveritySuccess,
    required this.signalSeveritySuccess,
    required this.iconSeveritySuccess,
    required this.textSeveritySuccess,
    required this.borderSeveritySuccessIndicator,
    required this.bgSeverityInfo,
    required this.borderSeverityInfo,
    required this.signalSeverityInfo,
    required this.iconSeverityInfo,
    required this.textSeverityInfo,
    required this.borderSeverityInfoIndicator,
    required this.bgSeverityWarning,
    required this.borderSeverityWarning,
    required this.signalSeverityWarning,
    required this.iconSeverityWarning,
    required this.textSeverityWarning,
    required this.borderSeverityWarningIndicator,
    required this.bgSeverityMinor,
    required this.borderSeverityMinor,
    required this.signalSeverityMinor,
    required this.iconSeverityMinor,
    required this.textSeverityMinor,
    required this.borderSeverityMinorIndicator,
    required this.bgSeverityMajor,
    required this.borderSeverityMajor,
    required this.signalSeverityMajor,
    required this.iconSeverityMajor,
    required this.textSeverityMajor,
    required this.borderSeverityMajorIndicator,
    required this.bgSeverityCritical,
    required this.borderSeverityCritical,
    required this.signalSeverityCritical,
    required this.iconSeverityCritical,
    required this.textSeverityCritical,
    required this.borderSeverityCriticalIndicator,
    required this.bgRiskLow,
    required this.borderRiskLow,
    required this.signalRiskLow,
    required this.iconRiskLow,
    required this.textRiskLow,
    required this.borderRiskLowIndicator,
    required this.bgRiskMedium,
    required this.borderRiskMedium,
    required this.signalRiskMedium,
    required this.iconRiskMedium,
    required this.textRiskMedium,
    required this.borderRiskMediumIndicator,
    required this.bgRiskHigh,
    required this.borderRiskHigh,
    required this.signalRiskHigh,
    required this.iconRiskHigh,
    required this.textRiskHigh,
    required this.borderRiskHighIndicator,
    required this.signalStatusUnknown,
    required this.signalStatusHealthy,
    required this.signalStatusWarning,
    required this.signalStatusMedium,
    required this.signalStatusUnhealthy,
    required this.focusRingColor,
  });

  /// `--vela-bg-global` · Figma `surface/global`
  final Color bgGlobal;
  /// `--vela-bg-container` · Figma `surface/container`
  final Color bgContainer;
  /// `--vela-bg-raised` · Figma `surface/raised`
  final Color bgRaised;
  /// `--vela-bg-hover` · Figma `surface/hover`
  final Color bgHover;
  /// `--vela-bg-tooltip` · Figma `surface/tooltip`
  final Color bgTooltip;
  /// `--vela-bg-inactive` · Figma `surface/inactive`
  final Color bgInactive;
  /// `--vela-bg-selected` · Figma `surface/selected`
  final Color bgSelected;
  /// `--vela-primary-tint` · Figma `surface/primary-tint`
  final Color primaryTint;
  /// `--vela-primary-active-bg` · Figma `surface/primary-active`
  final Color primaryActiveBg;
  /// `--vela-border-default` · Figma `border/default`
  final Color borderDefault;
  /// `--vela-border-subtle` · Figma `border/subtle`
  final Color borderSubtle;
  /// `--vela-border-active` · Figma `border/active`
  final Color borderActive;
  /// `--vela-border-inactive` · Figma `border/inactive`
  final Color borderInactive;
  /// `--vela-border-action` · Figma `border/action`
  final Color borderAction;
  /// `--vela-text-default` · Figma `text/default`
  final Color textDefault;
  /// `--vela-text-heading` · Figma `text/heading`
  final Color textHeading;
  /// `--vela-text-de-emphasized` · Figma `text/de-emphasized`
  final Color textDeEmphasized;
  /// `--vela-text-inactive` · Figma `text/inactive`
  final Color textInactive;
  /// `--vela-text-link` · Figma `text/link`
  final Color textLink;
  /// `--vela-text-on-brand` · Figma `text/on-brand`
  final Color textOnBrand;
  /// `--vela-text-on-tint` · Figma `text/on-tint`
  final Color textOnTint;
  /// `--vela-text-error` · Figma `text/error`
  final Color textError;
  /// `--vela-icon-default` · Figma `icon/default`
  final Color iconDefault;
  /// `--vela-icon-strong` · Figma `icon/strong`
  final Color iconStrong;
  /// `--vela-icon-selected` · Figma `icon/selected`
  final Color iconSelected;
  /// `--vela-icon-disabled` · Figma `icon/disabled`
  final Color iconDisabled;
  /// `--vela-icon-on-brand` · Figma `icon/on-brand`
  final Color iconOnBrand;
  /// `--vela-btn-primary-bg` · Figma `button/primary-bg`
  final Color btnPrimaryBg;
  /// `--vela-btn-primary-hover-bg` · Figma `button/primary-hover-bg`
  final Color btnPrimaryHoverBg;
  /// `--vela-btn-primary-border` · Figma `button/primary-border`
  final Color btnPrimaryBorder;
  /// `--vela-btn-primary-text` · Figma `button/primary-text`
  final Color btnPrimaryText;
  /// `--vela-btn-standard-bg` · Figma `button/standard-bg`
  final Color btnStandardBg;
  /// `--vela-btn-standard-hover-bg` · Figma `button/standard-hover-bg`
  final Color btnStandardHoverBg;
  /// `--vela-btn-standard-text` · Figma `button/standard-text`
  final Color btnStandardText;
  /// `--vela-btn-hollow-primary-text` · Figma `button/hollow-primary-text`
  final Color btnHollowPrimaryText;
  /// `--vela-btn-hollow-primary-border` · Figma `button/hollow-primary-border`
  final Color btnHollowPrimaryBorder;
  /// `--vela-btn-disabled-bg` · Figma `button/disabled-bg`
  final Color btnDisabledBg;
  /// `--vela-btn-disabled-text` · Figma `button/disabled-text`
  final Color btnDisabledText;
  /// `--vela-btn-destructive-bg` · Figma `button/destructive-bg`
  final Color btnDestructiveBg;
  /// `--vela-btn-destructive-hover-bg` · Figma `button/destructive-hover-bg`
  final Color btnDestructiveHoverBg;
  /// `--vela-btn-destructive-text` · Figma `button/destructive-text`
  final Color btnDestructiveText;
  /// `--vela-btn-destructive-hollow-text` · Figma `button/destructive-hollow-text`
  final Color btnDestructiveHollowText;
  /// `--vela-btn-standard-border` · Figma `button/standard-border`
  final Color btnStandardBorder;
  /// `--vela-btn-hollow-hover-bg` · Figma `button/hollow-hover-bg`
  final Color btnHollowHoverBg;
  /// `--vela-control-bg` · Figma `control/bg`
  final Color controlBg;
  /// `--vela-control-border` · Figma `control/border`
  final Color controlBorder;
  /// `--vela-control-border-hover` · Figma `control/border-hover`
  final Color controlBorderHover;
  /// `--vela-control-border-active` · Figma `control/border-active`
  final Color controlBorderActive;
  /// `--vela-control-border-error` · Figma `control/border-error`
  final Color controlBorderError;
  /// `--vela-control-bg-disabled` · Figma `control/bg-disabled`
  final Color controlBgDisabled;
  /// `--vela-control-placeholder` · Figma `control/placeholder`
  final Color controlPlaceholder;
  /// `--vela-toggle-off-bg` · Figma `control/toggle-off-bg`
  final Color toggleOffBg;
  /// `--vela-toggle-on-bg` · Figma `control/toggle-on-bg`
  final Color toggleOnBg;
  /// `--vela-toggle-knob` · Figma `control/toggle-knob`
  final Color toggleKnob;
  /// `--vela-bg-severity-success` · Figma `severity/success/bg`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color bgSeveritySuccess;
  /// `--vela-border-severity-success` · Figma `severity/success/border`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeveritySuccess;
  /// `--vela-signal-severity-success` · Figma `severity/success/signal`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color signalSeveritySuccess;
  /// `--vela-icon-severity-success` · Figma `severity/success/icon`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color iconSeveritySuccess;
  /// `--vela-text-severity-success` · Figma `severity/success/text`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color textSeveritySuccess;
  /// `--vela-border-severity-success-indicator` · Figma `severity/success/indicator`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeveritySuccessIndicator;
  /// `--vela-bg-severity-info` · Figma `severity/info/bg`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color bgSeverityInfo;
  /// `--vela-border-severity-info` · Figma `severity/info/border`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeverityInfo;
  /// `--vela-signal-severity-info` · Figma `severity/info/signal`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color signalSeverityInfo;
  /// `--vela-icon-severity-info` · Figma `severity/info/icon`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color iconSeverityInfo;
  /// `--vela-text-severity-info` · Figma `severity/info/text`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color textSeverityInfo;
  /// `--vela-border-severity-info-indicator` · Figma `severity/info/indicator`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeverityInfoIndicator;
  /// `--vela-bg-severity-warning` · Figma `severity/warning/bg`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color bgSeverityWarning;
  /// `--vela-border-severity-warning` · Figma `severity/warning/border`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeverityWarning;
  /// `--vela-signal-severity-warning` · Figma `severity/warning/signal`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color signalSeverityWarning;
  /// `--vela-icon-severity-warning` · Figma `severity/warning/icon`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color iconSeverityWarning;
  /// `--vela-text-severity-warning` · Figma `severity/warning/text`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color textSeverityWarning;
  /// `--vela-border-severity-warning-indicator` · Figma `severity/warning/indicator`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeverityWarningIndicator;
  /// `--vela-bg-severity-minor` · Figma `severity/minor/bg`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color bgSeverityMinor;
  /// `--vela-border-severity-minor` · Figma `severity/minor/border`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeverityMinor;
  /// `--vela-signal-severity-minor` · Figma `severity/minor/signal`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color signalSeverityMinor;
  /// `--vela-icon-severity-minor` · Figma `severity/minor/icon`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color iconSeverityMinor;
  /// `--vela-text-severity-minor` · Figma `severity/minor/text`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color textSeverityMinor;
  /// `--vela-border-severity-minor-indicator` · Figma `severity/minor/indicator`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeverityMinorIndicator;
  /// `--vela-bg-severity-major` · Figma `severity/major/bg`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color bgSeverityMajor;
  /// `--vela-border-severity-major` · Figma `severity/major/border`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeverityMajor;
  /// `--vela-signal-severity-major` · Figma `severity/major/signal`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color signalSeverityMajor;
  /// `--vela-icon-severity-major` · Figma `severity/major/icon`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color iconSeverityMajor;
  /// `--vela-text-severity-major` · Figma `severity/major/text`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color textSeverityMajor;
  /// `--vela-border-severity-major-indicator` · Figma `severity/major/indicator`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeverityMajorIndicator;
  /// `--vela-bg-severity-critical` · Figma `severity/critical/bg`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color bgSeverityCritical;
  /// `--vela-border-severity-critical` · Figma `severity/critical/border`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeverityCritical;
  /// `--vela-signal-severity-critical` · Figma `severity/critical/signal`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color signalSeverityCritical;
  /// `--vela-icon-severity-critical` · Figma `severity/critical/icon`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color iconSeverityCritical;
  /// `--vela-text-severity-critical` · Figma `severity/critical/text`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color textSeverityCritical;
  /// `--vela-border-severity-critical-indicator` · Figma `severity/critical/indicator`
  /// Severity describes events. Never interchange with Risk or Status.
  final Color borderSeverityCriticalIndicator;
  /// `--vela-bg-risk-low` · Figma `risk/low/bg`
  /// Risk describes scoring. There is no "critical risk".
  final Color bgRiskLow;
  /// `--vela-border-risk-low` · Figma `risk/low/border`
  /// Risk describes scoring. There is no "critical risk".
  final Color borderRiskLow;
  /// `--vela-signal-risk-low` · Figma `risk/low/signal`
  /// Risk describes scoring. There is no "critical risk".
  final Color signalRiskLow;
  /// `--vela-icon-risk-low` · Figma `risk/low/icon`
  /// Risk describes scoring. There is no "critical risk".
  final Color iconRiskLow;
  /// `--vela-text-risk-low` · Figma `risk/low/text`
  /// Risk describes scoring. There is no "critical risk".
  final Color textRiskLow;
  /// `--vela-border-risk-low-indicator` · Figma `risk/low/indicator`
  /// Risk describes scoring. There is no "critical risk".
  final Color borderRiskLowIndicator;
  /// `--vela-bg-risk-medium` · Figma `risk/medium/bg`
  /// Risk describes scoring. There is no "critical risk".
  final Color bgRiskMedium;
  /// `--vela-border-risk-medium` · Figma `risk/medium/border`
  /// Risk describes scoring. There is no "critical risk".
  final Color borderRiskMedium;
  /// `--vela-signal-risk-medium` · Figma `risk/medium/signal`
  /// Risk describes scoring. There is no "critical risk".
  final Color signalRiskMedium;
  /// `--vela-icon-risk-medium` · Figma `risk/medium/icon`
  /// Risk describes scoring. There is no "critical risk".
  final Color iconRiskMedium;
  /// `--vela-text-risk-medium` · Figma `risk/medium/text`
  /// Risk describes scoring. There is no "critical risk".
  final Color textRiskMedium;
  /// `--vela-border-risk-medium-indicator` · Figma `risk/medium/indicator`
  /// Risk describes scoring. There is no "critical risk".
  final Color borderRiskMediumIndicator;
  /// `--vela-bg-risk-high` · Figma `risk/high/bg`
  /// Risk describes scoring. There is no "critical risk".
  final Color bgRiskHigh;
  /// `--vela-border-risk-high` · Figma `risk/high/border`
  /// Risk describes scoring. There is no "critical risk".
  final Color borderRiskHigh;
  /// `--vela-signal-risk-high` · Figma `risk/high/signal`
  /// Risk describes scoring. There is no "critical risk".
  final Color signalRiskHigh;
  /// `--vela-icon-risk-high` · Figma `risk/high/icon`
  /// Risk describes scoring. There is no "critical risk".
  final Color iconRiskHigh;
  /// `--vela-text-risk-high` · Figma `risk/high/text`
  /// Risk describes scoring. There is no "critical risk".
  final Color textRiskHigh;
  /// `--vela-border-risk-high-indicator` · Figma `risk/high/indicator`
  /// Risk describes scoring. There is no "critical risk".
  final Color borderRiskHighIndicator;
  /// `--vela-signal-status-unknown` · Figma `status/unknown`
  /// Status Indicator dots only. Five states, neither severity nor risk.
  final Color signalStatusUnknown;
  /// `--vela-signal-status-healthy` · Figma `status/healthy`
  /// Status Indicator dots only. Five states, neither severity nor risk.
  final Color signalStatusHealthy;
  /// `--vela-signal-status-warning` · Figma `status/warning`
  /// Status Indicator dots only. Five states, neither severity nor risk.
  final Color signalStatusWarning;
  /// `--vela-signal-status-medium` · Figma `status/medium`
  /// Status Indicator dots only. Five states, neither severity nor risk.
  final Color signalStatusMedium;
  /// `--vela-signal-status-unhealthy` · Figma `status/unhealthy`
  /// Status Indicator dots only. Five states, neither severity nor risk.
  final Color signalStatusUnhealthy;
  /// `--vela-focus-ring-color` · Figma `focus/ring`
  /// One focus treatment for the whole kit.
  final Color focusRingColor;

  /// The light theme, resolved to primitives exactly as tokens.css resolves it.
  static const VelaColors light = VelaColors(
    bgGlobal: VelaPrimitives.white,
    bgContainer: VelaPrimitives.grey100,
    bgRaised: VelaPrimitives.white,
    bgHover: VelaPrimitives.grey100,
    bgTooltip: VelaPrimitives.grey800,
    bgInactive: VelaPrimitives.grey100,
    bgSelected: VelaPrimitives.blue100,
    primaryTint: VelaPrimitives.blue100,
    primaryActiveBg: VelaPrimitives.primary500,
    borderDefault: VelaPrimitives.grey500,
    borderSubtle: VelaPrimitives.grey200,
    borderActive: VelaPrimitives.primary500,
    borderInactive: VelaPrimitives.grey200,
    borderAction: VelaPrimitives.grey700,
    textDefault: VelaPrimitives.grey700,
    textHeading: VelaPrimitives.black,
    textDeEmphasized: VelaPrimitives.grey600,
    textInactive: VelaPrimitives.grey400,
    textLink: VelaPrimitives.primary500,
    textOnBrand: VelaPrimitives.white,
    textOnTint: VelaPrimitives.grey700,
    textError: VelaPrimitives.red700,
    iconDefault: VelaPrimitives.grey500,
    iconStrong: VelaPrimitives.grey700,
    iconSelected: VelaPrimitives.primary500,
    iconDisabled: VelaPrimitives.grey300,
    iconOnBrand: VelaPrimitives.white,
    btnPrimaryBg: VelaPrimitives.primary500,
    btnPrimaryHoverBg: VelaPrimitives.primary600,
    btnPrimaryBorder: VelaPrimitives.primary500,
    btnPrimaryText: VelaPrimitives.white,
    btnStandardBg: VelaPrimitives.grey100,
    btnStandardHoverBg: VelaPrimitives.grey200,
    btnStandardText: VelaPrimitives.grey700,
    btnHollowPrimaryText: VelaPrimitives.primary500,
    btnHollowPrimaryBorder: VelaPrimitives.primary500,
    btnDisabledBg: VelaPrimitives.grey200,
    btnDisabledText: VelaPrimitives.grey400,
    btnDestructiveBg: VelaPrimitives.red700,
    btnDestructiveHoverBg: VelaPrimitives.critical500,
    btnDestructiveText: VelaPrimitives.white,
    btnDestructiveHollowText: VelaPrimitives.red700,
    btnStandardBorder: VelaPrimitives.grey600,
    btnHollowHoverBg: VelaPrimitives.blue100,
    controlBg: VelaPrimitives.white,
    controlBorder: VelaPrimitives.grey500,
    controlBorderHover: VelaPrimitives.grey500,
    controlBorderActive: VelaPrimitives.primary500,
    controlBorderError: VelaPrimitives.red500,
    controlBgDisabled: VelaPrimitives.grey100,
    controlPlaceholder: VelaPrimitives.grey600,
    toggleOffBg: VelaPrimitives.grey400,
    toggleOnBg: VelaPrimitives.primary500,
    toggleKnob: VelaPrimitives.white,
    bgSeveritySuccess: VelaPrimitives.green100,
    borderSeveritySuccess: VelaPrimitives.green300,
    signalSeveritySuccess: VelaPrimitives.green500,
    iconSeveritySuccess: VelaPrimitives.green800,
    textSeveritySuccess: VelaPrimitives.green800,
    borderSeveritySuccessIndicator: VelaPrimitives.green700,
    bgSeverityInfo: VelaPrimitives.blue100,
    borderSeverityInfo: VelaPrimitives.blue300,
    signalSeverityInfo: VelaPrimitives.blue500,
    iconSeverityInfo: VelaPrimitives.blue700,
    textSeverityInfo: VelaPrimitives.blue700,
    borderSeverityInfoIndicator: VelaPrimitives.blue700,
    bgSeverityWarning: VelaPrimitives.yellow100,
    borderSeverityWarning: VelaPrimitives.yellow300,
    signalSeverityWarning: VelaPrimitives.yellow500,
    iconSeverityWarning: VelaPrimitives.yellow800,
    textSeverityWarning: VelaPrimitives.yellow800,
    borderSeverityWarningIndicator: VelaPrimitives.yellow700,
    bgSeverityMinor: VelaPrimitives.orange100,
    borderSeverityMinor: VelaPrimitives.orange300,
    signalSeverityMinor: VelaPrimitives.orange500,
    iconSeverityMinor: VelaPrimitives.orange700,
    textSeverityMinor: VelaPrimitives.orange700,
    borderSeverityMinorIndicator: VelaPrimitives.orange700,
    bgSeverityMajor: VelaPrimitives.red100,
    borderSeverityMajor: VelaPrimitives.red300,
    signalSeverityMajor: VelaPrimitives.red500,
    iconSeverityMajor: VelaPrimitives.red700,
    textSeverityMajor: VelaPrimitives.red700,
    borderSeverityMajorIndicator: VelaPrimitives.red700,
    bgSeverityCritical: VelaPrimitives.critical100,
    borderSeverityCritical: VelaPrimitives.critical300,
    signalSeverityCritical: VelaPrimitives.critical500,
    iconSeverityCritical: VelaPrimitives.critical700,
    textSeverityCritical: VelaPrimitives.critical700,
    borderSeverityCriticalIndicator: VelaPrimitives.critical700,
    bgRiskLow: VelaPrimitives.green100,
    borderRiskLow: VelaPrimitives.green300,
    signalRiskLow: VelaPrimitives.green500,
    iconRiskLow: VelaPrimitives.green800,
    textRiskLow: VelaPrimitives.green800,
    borderRiskLowIndicator: VelaPrimitives.green700,
    bgRiskMedium: VelaPrimitives.yellow100,
    borderRiskMedium: VelaPrimitives.yellow300,
    signalRiskMedium: VelaPrimitives.yellow500,
    iconRiskMedium: VelaPrimitives.yellow800,
    textRiskMedium: VelaPrimitives.yellow800,
    borderRiskMediumIndicator: VelaPrimitives.yellow700,
    bgRiskHigh: VelaPrimitives.red100,
    borderRiskHigh: VelaPrimitives.red300,
    signalRiskHigh: VelaPrimitives.red500,
    iconRiskHigh: VelaPrimitives.red700,
    textRiskHigh: VelaPrimitives.red700,
    borderRiskHighIndicator: VelaPrimitives.red700,
    signalStatusUnknown: VelaPrimitives.grey500,
    signalStatusHealthy: VelaPrimitives.green700,
    signalStatusWarning: VelaPrimitives.yellow700,
    signalStatusMedium: VelaPrimitives.orange600,
    signalStatusUnhealthy: VelaPrimitives.red500,
    focusRingColor: VelaPrimitives.primary500,
  );

  /// The dark theme, resolved to primitives exactly as tokens.css resolves it.
  static const VelaColors dark = VelaColors(
    bgGlobal: VelaPrimitives.grey950,
    bgContainer: VelaPrimitives.grey900,
    bgRaised: VelaPrimitives.grey850,
    bgHover: VelaPrimitives.grey850,
    bgTooltip: VelaPrimitives.grey700,
    bgInactive: VelaPrimitives.grey900,
    bgSelected: VelaPrimitives.blue950,
    primaryTint: VelaPrimitives.blue950,
    primaryActiveBg: VelaPrimitives.primary500,
    borderDefault: VelaPrimitives.grey600,
    borderSubtle: VelaPrimitives.grey850,
    borderActive: VelaPrimitives.primary400,
    borderInactive: VelaPrimitives.grey850,
    borderAction: VelaPrimitives.grey500,
    textDefault: VelaPrimitives.grey300,
    textHeading: VelaPrimitives.grey50,
    textDeEmphasized: VelaPrimitives.grey500,
    textInactive: VelaPrimitives.grey700,
    textLink: VelaPrimitives.primary400,
    textOnBrand: VelaPrimitives.white,
    textOnTint: VelaPrimitives.grey300,
    textError: VelaPrimitives.red300,
    iconDefault: VelaPrimitives.grey500,
    iconStrong: VelaPrimitives.grey300,
    iconSelected: VelaPrimitives.primary400,
    iconDisabled: VelaPrimitives.grey700,
    iconOnBrand: VelaPrimitives.white,
    btnPrimaryBg: VelaPrimitives.primary500,
    btnPrimaryHoverBg: VelaPrimitives.primary400,
    btnPrimaryBorder: VelaPrimitives.primary500,
    btnPrimaryText: VelaPrimitives.white,
    btnStandardBg: VelaPrimitives.grey850,
    btnStandardHoverBg: VelaPrimitives.grey800,
    btnStandardText: VelaPrimitives.grey300,
    btnHollowPrimaryText: VelaPrimitives.primary300,
    btnHollowPrimaryBorder: VelaPrimitives.primary400,
    btnDisabledBg: VelaPrimitives.grey850,
    btnDisabledText: VelaPrimitives.grey700,
    btnDestructiveBg: VelaPrimitives.red700,
    btnDestructiveHoverBg: VelaPrimitives.red500,
    btnDestructiveText: VelaPrimitives.white,
    btnDestructiveHollowText: VelaPrimitives.red300,
    btnStandardBorder: VelaPrimitives.grey500,
    btnHollowHoverBg: VelaPrimitives.blue950,
    controlBg: VelaPrimitives.grey900,
    controlBorder: VelaPrimitives.grey600,
    controlBorderHover: VelaPrimitives.grey500,
    controlBorderActive: VelaPrimitives.primary400,
    controlBorderError: VelaPrimitives.red500,
    controlBgDisabled: VelaPrimitives.grey900,
    controlPlaceholder: VelaPrimitives.grey500,
    toggleOffBg: VelaPrimitives.grey700,
    toggleOnBg: VelaPrimitives.primary500,
    toggleKnob: VelaPrimitives.white,
    bgSeveritySuccess: VelaPrimitives.green950,
    borderSeveritySuccess: VelaPrimitives.green700,
    signalSeveritySuccess: VelaPrimitives.green500,
    iconSeveritySuccess: VelaPrimitives.green300,
    textSeveritySuccess: VelaPrimitives.green300,
    borderSeveritySuccessIndicator: VelaPrimitives.green500,
    bgSeverityInfo: VelaPrimitives.blue950,
    borderSeverityInfo: VelaPrimitives.blue700,
    signalSeverityInfo: VelaPrimitives.blue500,
    iconSeverityInfo: VelaPrimitives.blue300,
    textSeverityInfo: VelaPrimitives.blue300,
    borderSeverityInfoIndicator: VelaPrimitives.blue500,
    bgSeverityWarning: VelaPrimitives.yellow950,
    borderSeverityWarning: VelaPrimitives.yellow700,
    signalSeverityWarning: VelaPrimitives.yellow500,
    iconSeverityWarning: VelaPrimitives.yellow300,
    textSeverityWarning: VelaPrimitives.yellow300,
    borderSeverityWarningIndicator: VelaPrimitives.yellow500,
    bgSeverityMinor: VelaPrimitives.orange950,
    borderSeverityMinor: VelaPrimitives.orange700,
    signalSeverityMinor: VelaPrimitives.orange500,
    iconSeverityMinor: VelaPrimitives.orange300,
    textSeverityMinor: VelaPrimitives.orange300,
    borderSeverityMinorIndicator: VelaPrimitives.orange500,
    bgSeverityMajor: VelaPrimitives.red950,
    borderSeverityMajor: VelaPrimitives.red700,
    signalSeverityMajor: VelaPrimitives.red500,
    iconSeverityMajor: VelaPrimitives.red300,
    textSeverityMajor: VelaPrimitives.red300,
    borderSeverityMajorIndicator: VelaPrimitives.red500,
    bgSeverityCritical: VelaPrimitives.critical950,
    borderSeverityCritical: VelaPrimitives.critical500,
    signalSeverityCritical: VelaPrimitives.critical300,
    iconSeverityCritical: VelaPrimitives.critical300,
    textSeverityCritical: VelaPrimitives.critical300,
    borderSeverityCriticalIndicator: VelaPrimitives.critical300,
    bgRiskLow: VelaPrimitives.green950,
    borderRiskLow: VelaPrimitives.green700,
    signalRiskLow: VelaPrimitives.green500,
    iconRiskLow: VelaPrimitives.green300,
    textRiskLow: VelaPrimitives.green300,
    borderRiskLowIndicator: VelaPrimitives.green500,
    bgRiskMedium: VelaPrimitives.yellow950,
    borderRiskMedium: VelaPrimitives.yellow700,
    signalRiskMedium: VelaPrimitives.yellow500,
    iconRiskMedium: VelaPrimitives.yellow300,
    textRiskMedium: VelaPrimitives.yellow300,
    borderRiskMediumIndicator: VelaPrimitives.yellow500,
    bgRiskHigh: VelaPrimitives.red950,
    borderRiskHigh: VelaPrimitives.red700,
    signalRiskHigh: VelaPrimitives.red500,
    iconRiskHigh: VelaPrimitives.red300,
    textRiskHigh: VelaPrimitives.red300,
    borderRiskHighIndicator: VelaPrimitives.red500,
    signalStatusUnknown: VelaPrimitives.grey500,
    signalStatusHealthy: VelaPrimitives.green500,
    signalStatusWarning: VelaPrimitives.yellow500,
    signalStatusMedium: VelaPrimitives.orange500,
    signalStatusUnhealthy: VelaPrimitives.red500,
    focusRingColor: VelaPrimitives.primary400,
  );

  @override
  VelaColors copyWith({
    Color? bgGlobal,
    Color? bgContainer,
    Color? bgRaised,
    Color? bgHover,
    Color? bgTooltip,
    Color? bgInactive,
    Color? bgSelected,
    Color? primaryTint,
    Color? primaryActiveBg,
    Color? borderDefault,
    Color? borderSubtle,
    Color? borderActive,
    Color? borderInactive,
    Color? borderAction,
    Color? textDefault,
    Color? textHeading,
    Color? textDeEmphasized,
    Color? textInactive,
    Color? textLink,
    Color? textOnBrand,
    Color? textOnTint,
    Color? textError,
    Color? iconDefault,
    Color? iconStrong,
    Color? iconSelected,
    Color? iconDisabled,
    Color? iconOnBrand,
    Color? btnPrimaryBg,
    Color? btnPrimaryHoverBg,
    Color? btnPrimaryBorder,
    Color? btnPrimaryText,
    Color? btnStandardBg,
    Color? btnStandardHoverBg,
    Color? btnStandardText,
    Color? btnHollowPrimaryText,
    Color? btnHollowPrimaryBorder,
    Color? btnDisabledBg,
    Color? btnDisabledText,
    Color? btnDestructiveBg,
    Color? btnDestructiveHoverBg,
    Color? btnDestructiveText,
    Color? btnDestructiveHollowText,
    Color? btnStandardBorder,
    Color? btnHollowHoverBg,
    Color? controlBg,
    Color? controlBorder,
    Color? controlBorderHover,
    Color? controlBorderActive,
    Color? controlBorderError,
    Color? controlBgDisabled,
    Color? controlPlaceholder,
    Color? toggleOffBg,
    Color? toggleOnBg,
    Color? toggleKnob,
    Color? bgSeveritySuccess,
    Color? borderSeveritySuccess,
    Color? signalSeveritySuccess,
    Color? iconSeveritySuccess,
    Color? textSeveritySuccess,
    Color? borderSeveritySuccessIndicator,
    Color? bgSeverityInfo,
    Color? borderSeverityInfo,
    Color? signalSeverityInfo,
    Color? iconSeverityInfo,
    Color? textSeverityInfo,
    Color? borderSeverityInfoIndicator,
    Color? bgSeverityWarning,
    Color? borderSeverityWarning,
    Color? signalSeverityWarning,
    Color? iconSeverityWarning,
    Color? textSeverityWarning,
    Color? borderSeverityWarningIndicator,
    Color? bgSeverityMinor,
    Color? borderSeverityMinor,
    Color? signalSeverityMinor,
    Color? iconSeverityMinor,
    Color? textSeverityMinor,
    Color? borderSeverityMinorIndicator,
    Color? bgSeverityMajor,
    Color? borderSeverityMajor,
    Color? signalSeverityMajor,
    Color? iconSeverityMajor,
    Color? textSeverityMajor,
    Color? borderSeverityMajorIndicator,
    Color? bgSeverityCritical,
    Color? borderSeverityCritical,
    Color? signalSeverityCritical,
    Color? iconSeverityCritical,
    Color? textSeverityCritical,
    Color? borderSeverityCriticalIndicator,
    Color? bgRiskLow,
    Color? borderRiskLow,
    Color? signalRiskLow,
    Color? iconRiskLow,
    Color? textRiskLow,
    Color? borderRiskLowIndicator,
    Color? bgRiskMedium,
    Color? borderRiskMedium,
    Color? signalRiskMedium,
    Color? iconRiskMedium,
    Color? textRiskMedium,
    Color? borderRiskMediumIndicator,
    Color? bgRiskHigh,
    Color? borderRiskHigh,
    Color? signalRiskHigh,
    Color? iconRiskHigh,
    Color? textRiskHigh,
    Color? borderRiskHighIndicator,
    Color? signalStatusUnknown,
    Color? signalStatusHealthy,
    Color? signalStatusWarning,
    Color? signalStatusMedium,
    Color? signalStatusUnhealthy,
    Color? focusRingColor,
  }) {
    return VelaColors(
      bgGlobal: bgGlobal ?? this.bgGlobal,
      bgContainer: bgContainer ?? this.bgContainer,
      bgRaised: bgRaised ?? this.bgRaised,
      bgHover: bgHover ?? this.bgHover,
      bgTooltip: bgTooltip ?? this.bgTooltip,
      bgInactive: bgInactive ?? this.bgInactive,
      bgSelected: bgSelected ?? this.bgSelected,
      primaryTint: primaryTint ?? this.primaryTint,
      primaryActiveBg: primaryActiveBg ?? this.primaryActiveBg,
      borderDefault: borderDefault ?? this.borderDefault,
      borderSubtle: borderSubtle ?? this.borderSubtle,
      borderActive: borderActive ?? this.borderActive,
      borderInactive: borderInactive ?? this.borderInactive,
      borderAction: borderAction ?? this.borderAction,
      textDefault: textDefault ?? this.textDefault,
      textHeading: textHeading ?? this.textHeading,
      textDeEmphasized: textDeEmphasized ?? this.textDeEmphasized,
      textInactive: textInactive ?? this.textInactive,
      textLink: textLink ?? this.textLink,
      textOnBrand: textOnBrand ?? this.textOnBrand,
      textOnTint: textOnTint ?? this.textOnTint,
      textError: textError ?? this.textError,
      iconDefault: iconDefault ?? this.iconDefault,
      iconStrong: iconStrong ?? this.iconStrong,
      iconSelected: iconSelected ?? this.iconSelected,
      iconDisabled: iconDisabled ?? this.iconDisabled,
      iconOnBrand: iconOnBrand ?? this.iconOnBrand,
      btnPrimaryBg: btnPrimaryBg ?? this.btnPrimaryBg,
      btnPrimaryHoverBg: btnPrimaryHoverBg ?? this.btnPrimaryHoverBg,
      btnPrimaryBorder: btnPrimaryBorder ?? this.btnPrimaryBorder,
      btnPrimaryText: btnPrimaryText ?? this.btnPrimaryText,
      btnStandardBg: btnStandardBg ?? this.btnStandardBg,
      btnStandardHoverBg: btnStandardHoverBg ?? this.btnStandardHoverBg,
      btnStandardText: btnStandardText ?? this.btnStandardText,
      btnHollowPrimaryText: btnHollowPrimaryText ?? this.btnHollowPrimaryText,
      btnHollowPrimaryBorder: btnHollowPrimaryBorder ?? this.btnHollowPrimaryBorder,
      btnDisabledBg: btnDisabledBg ?? this.btnDisabledBg,
      btnDisabledText: btnDisabledText ?? this.btnDisabledText,
      btnDestructiveBg: btnDestructiveBg ?? this.btnDestructiveBg,
      btnDestructiveHoverBg: btnDestructiveHoverBg ?? this.btnDestructiveHoverBg,
      btnDestructiveText: btnDestructiveText ?? this.btnDestructiveText,
      btnDestructiveHollowText: btnDestructiveHollowText ?? this.btnDestructiveHollowText,
      btnStandardBorder: btnStandardBorder ?? this.btnStandardBorder,
      btnHollowHoverBg: btnHollowHoverBg ?? this.btnHollowHoverBg,
      controlBg: controlBg ?? this.controlBg,
      controlBorder: controlBorder ?? this.controlBorder,
      controlBorderHover: controlBorderHover ?? this.controlBorderHover,
      controlBorderActive: controlBorderActive ?? this.controlBorderActive,
      controlBorderError: controlBorderError ?? this.controlBorderError,
      controlBgDisabled: controlBgDisabled ?? this.controlBgDisabled,
      controlPlaceholder: controlPlaceholder ?? this.controlPlaceholder,
      toggleOffBg: toggleOffBg ?? this.toggleOffBg,
      toggleOnBg: toggleOnBg ?? this.toggleOnBg,
      toggleKnob: toggleKnob ?? this.toggleKnob,
      bgSeveritySuccess: bgSeveritySuccess ?? this.bgSeveritySuccess,
      borderSeveritySuccess: borderSeveritySuccess ?? this.borderSeveritySuccess,
      signalSeveritySuccess: signalSeveritySuccess ?? this.signalSeveritySuccess,
      iconSeveritySuccess: iconSeveritySuccess ?? this.iconSeveritySuccess,
      textSeveritySuccess: textSeveritySuccess ?? this.textSeveritySuccess,
      borderSeveritySuccessIndicator: borderSeveritySuccessIndicator ?? this.borderSeveritySuccessIndicator,
      bgSeverityInfo: bgSeverityInfo ?? this.bgSeverityInfo,
      borderSeverityInfo: borderSeverityInfo ?? this.borderSeverityInfo,
      signalSeverityInfo: signalSeverityInfo ?? this.signalSeverityInfo,
      iconSeverityInfo: iconSeverityInfo ?? this.iconSeverityInfo,
      textSeverityInfo: textSeverityInfo ?? this.textSeverityInfo,
      borderSeverityInfoIndicator: borderSeverityInfoIndicator ?? this.borderSeverityInfoIndicator,
      bgSeverityWarning: bgSeverityWarning ?? this.bgSeverityWarning,
      borderSeverityWarning: borderSeverityWarning ?? this.borderSeverityWarning,
      signalSeverityWarning: signalSeverityWarning ?? this.signalSeverityWarning,
      iconSeverityWarning: iconSeverityWarning ?? this.iconSeverityWarning,
      textSeverityWarning: textSeverityWarning ?? this.textSeverityWarning,
      borderSeverityWarningIndicator: borderSeverityWarningIndicator ?? this.borderSeverityWarningIndicator,
      bgSeverityMinor: bgSeverityMinor ?? this.bgSeverityMinor,
      borderSeverityMinor: borderSeverityMinor ?? this.borderSeverityMinor,
      signalSeverityMinor: signalSeverityMinor ?? this.signalSeverityMinor,
      iconSeverityMinor: iconSeverityMinor ?? this.iconSeverityMinor,
      textSeverityMinor: textSeverityMinor ?? this.textSeverityMinor,
      borderSeverityMinorIndicator: borderSeverityMinorIndicator ?? this.borderSeverityMinorIndicator,
      bgSeverityMajor: bgSeverityMajor ?? this.bgSeverityMajor,
      borderSeverityMajor: borderSeverityMajor ?? this.borderSeverityMajor,
      signalSeverityMajor: signalSeverityMajor ?? this.signalSeverityMajor,
      iconSeverityMajor: iconSeverityMajor ?? this.iconSeverityMajor,
      textSeverityMajor: textSeverityMajor ?? this.textSeverityMajor,
      borderSeverityMajorIndicator: borderSeverityMajorIndicator ?? this.borderSeverityMajorIndicator,
      bgSeverityCritical: bgSeverityCritical ?? this.bgSeverityCritical,
      borderSeverityCritical: borderSeverityCritical ?? this.borderSeverityCritical,
      signalSeverityCritical: signalSeverityCritical ?? this.signalSeverityCritical,
      iconSeverityCritical: iconSeverityCritical ?? this.iconSeverityCritical,
      textSeverityCritical: textSeverityCritical ?? this.textSeverityCritical,
      borderSeverityCriticalIndicator: borderSeverityCriticalIndicator ?? this.borderSeverityCriticalIndicator,
      bgRiskLow: bgRiskLow ?? this.bgRiskLow,
      borderRiskLow: borderRiskLow ?? this.borderRiskLow,
      signalRiskLow: signalRiskLow ?? this.signalRiskLow,
      iconRiskLow: iconRiskLow ?? this.iconRiskLow,
      textRiskLow: textRiskLow ?? this.textRiskLow,
      borderRiskLowIndicator: borderRiskLowIndicator ?? this.borderRiskLowIndicator,
      bgRiskMedium: bgRiskMedium ?? this.bgRiskMedium,
      borderRiskMedium: borderRiskMedium ?? this.borderRiskMedium,
      signalRiskMedium: signalRiskMedium ?? this.signalRiskMedium,
      iconRiskMedium: iconRiskMedium ?? this.iconRiskMedium,
      textRiskMedium: textRiskMedium ?? this.textRiskMedium,
      borderRiskMediumIndicator: borderRiskMediumIndicator ?? this.borderRiskMediumIndicator,
      bgRiskHigh: bgRiskHigh ?? this.bgRiskHigh,
      borderRiskHigh: borderRiskHigh ?? this.borderRiskHigh,
      signalRiskHigh: signalRiskHigh ?? this.signalRiskHigh,
      iconRiskHigh: iconRiskHigh ?? this.iconRiskHigh,
      textRiskHigh: textRiskHigh ?? this.textRiskHigh,
      borderRiskHighIndicator: borderRiskHighIndicator ?? this.borderRiskHighIndicator,
      signalStatusUnknown: signalStatusUnknown ?? this.signalStatusUnknown,
      signalStatusHealthy: signalStatusHealthy ?? this.signalStatusHealthy,
      signalStatusWarning: signalStatusWarning ?? this.signalStatusWarning,
      signalStatusMedium: signalStatusMedium ?? this.signalStatusMedium,
      signalStatusUnhealthy: signalStatusUnhealthy ?? this.signalStatusUnhealthy,
      focusRingColor: focusRingColor ?? this.focusRingColor,
    );
  }

  @override
  VelaColors lerp(ThemeExtension<VelaColors>? other, double t) {
    if (other is! VelaColors) return this;
    return VelaColors(
      bgGlobal: Color.lerp(bgGlobal, other.bgGlobal, t)!,
      bgContainer: Color.lerp(bgContainer, other.bgContainer, t)!,
      bgRaised: Color.lerp(bgRaised, other.bgRaised, t)!,
      bgHover: Color.lerp(bgHover, other.bgHover, t)!,
      bgTooltip: Color.lerp(bgTooltip, other.bgTooltip, t)!,
      bgInactive: Color.lerp(bgInactive, other.bgInactive, t)!,
      bgSelected: Color.lerp(bgSelected, other.bgSelected, t)!,
      primaryTint: Color.lerp(primaryTint, other.primaryTint, t)!,
      primaryActiveBg: Color.lerp(primaryActiveBg, other.primaryActiveBg, t)!,
      borderDefault: Color.lerp(borderDefault, other.borderDefault, t)!,
      borderSubtle: Color.lerp(borderSubtle, other.borderSubtle, t)!,
      borderActive: Color.lerp(borderActive, other.borderActive, t)!,
      borderInactive: Color.lerp(borderInactive, other.borderInactive, t)!,
      borderAction: Color.lerp(borderAction, other.borderAction, t)!,
      textDefault: Color.lerp(textDefault, other.textDefault, t)!,
      textHeading: Color.lerp(textHeading, other.textHeading, t)!,
      textDeEmphasized: Color.lerp(textDeEmphasized, other.textDeEmphasized, t)!,
      textInactive: Color.lerp(textInactive, other.textInactive, t)!,
      textLink: Color.lerp(textLink, other.textLink, t)!,
      textOnBrand: Color.lerp(textOnBrand, other.textOnBrand, t)!,
      textOnTint: Color.lerp(textOnTint, other.textOnTint, t)!,
      textError: Color.lerp(textError, other.textError, t)!,
      iconDefault: Color.lerp(iconDefault, other.iconDefault, t)!,
      iconStrong: Color.lerp(iconStrong, other.iconStrong, t)!,
      iconSelected: Color.lerp(iconSelected, other.iconSelected, t)!,
      iconDisabled: Color.lerp(iconDisabled, other.iconDisabled, t)!,
      iconOnBrand: Color.lerp(iconOnBrand, other.iconOnBrand, t)!,
      btnPrimaryBg: Color.lerp(btnPrimaryBg, other.btnPrimaryBg, t)!,
      btnPrimaryHoverBg: Color.lerp(btnPrimaryHoverBg, other.btnPrimaryHoverBg, t)!,
      btnPrimaryBorder: Color.lerp(btnPrimaryBorder, other.btnPrimaryBorder, t)!,
      btnPrimaryText: Color.lerp(btnPrimaryText, other.btnPrimaryText, t)!,
      btnStandardBg: Color.lerp(btnStandardBg, other.btnStandardBg, t)!,
      btnStandardHoverBg: Color.lerp(btnStandardHoverBg, other.btnStandardHoverBg, t)!,
      btnStandardText: Color.lerp(btnStandardText, other.btnStandardText, t)!,
      btnHollowPrimaryText: Color.lerp(btnHollowPrimaryText, other.btnHollowPrimaryText, t)!,
      btnHollowPrimaryBorder: Color.lerp(btnHollowPrimaryBorder, other.btnHollowPrimaryBorder, t)!,
      btnDisabledBg: Color.lerp(btnDisabledBg, other.btnDisabledBg, t)!,
      btnDisabledText: Color.lerp(btnDisabledText, other.btnDisabledText, t)!,
      btnDestructiveBg: Color.lerp(btnDestructiveBg, other.btnDestructiveBg, t)!,
      btnDestructiveHoverBg: Color.lerp(btnDestructiveHoverBg, other.btnDestructiveHoverBg, t)!,
      btnDestructiveText: Color.lerp(btnDestructiveText, other.btnDestructiveText, t)!,
      btnDestructiveHollowText: Color.lerp(btnDestructiveHollowText, other.btnDestructiveHollowText, t)!,
      btnStandardBorder: Color.lerp(btnStandardBorder, other.btnStandardBorder, t)!,
      btnHollowHoverBg: Color.lerp(btnHollowHoverBg, other.btnHollowHoverBg, t)!,
      controlBg: Color.lerp(controlBg, other.controlBg, t)!,
      controlBorder: Color.lerp(controlBorder, other.controlBorder, t)!,
      controlBorderHover: Color.lerp(controlBorderHover, other.controlBorderHover, t)!,
      controlBorderActive: Color.lerp(controlBorderActive, other.controlBorderActive, t)!,
      controlBorderError: Color.lerp(controlBorderError, other.controlBorderError, t)!,
      controlBgDisabled: Color.lerp(controlBgDisabled, other.controlBgDisabled, t)!,
      controlPlaceholder: Color.lerp(controlPlaceholder, other.controlPlaceholder, t)!,
      toggleOffBg: Color.lerp(toggleOffBg, other.toggleOffBg, t)!,
      toggleOnBg: Color.lerp(toggleOnBg, other.toggleOnBg, t)!,
      toggleKnob: Color.lerp(toggleKnob, other.toggleKnob, t)!,
      bgSeveritySuccess: Color.lerp(bgSeveritySuccess, other.bgSeveritySuccess, t)!,
      borderSeveritySuccess: Color.lerp(borderSeveritySuccess, other.borderSeveritySuccess, t)!,
      signalSeveritySuccess: Color.lerp(signalSeveritySuccess, other.signalSeveritySuccess, t)!,
      iconSeveritySuccess: Color.lerp(iconSeveritySuccess, other.iconSeveritySuccess, t)!,
      textSeveritySuccess: Color.lerp(textSeveritySuccess, other.textSeveritySuccess, t)!,
      borderSeveritySuccessIndicator: Color.lerp(borderSeveritySuccessIndicator, other.borderSeveritySuccessIndicator, t)!,
      bgSeverityInfo: Color.lerp(bgSeverityInfo, other.bgSeverityInfo, t)!,
      borderSeverityInfo: Color.lerp(borderSeverityInfo, other.borderSeverityInfo, t)!,
      signalSeverityInfo: Color.lerp(signalSeverityInfo, other.signalSeverityInfo, t)!,
      iconSeverityInfo: Color.lerp(iconSeverityInfo, other.iconSeverityInfo, t)!,
      textSeverityInfo: Color.lerp(textSeverityInfo, other.textSeverityInfo, t)!,
      borderSeverityInfoIndicator: Color.lerp(borderSeverityInfoIndicator, other.borderSeverityInfoIndicator, t)!,
      bgSeverityWarning: Color.lerp(bgSeverityWarning, other.bgSeverityWarning, t)!,
      borderSeverityWarning: Color.lerp(borderSeverityWarning, other.borderSeverityWarning, t)!,
      signalSeverityWarning: Color.lerp(signalSeverityWarning, other.signalSeverityWarning, t)!,
      iconSeverityWarning: Color.lerp(iconSeverityWarning, other.iconSeverityWarning, t)!,
      textSeverityWarning: Color.lerp(textSeverityWarning, other.textSeverityWarning, t)!,
      borderSeverityWarningIndicator: Color.lerp(borderSeverityWarningIndicator, other.borderSeverityWarningIndicator, t)!,
      bgSeverityMinor: Color.lerp(bgSeverityMinor, other.bgSeverityMinor, t)!,
      borderSeverityMinor: Color.lerp(borderSeverityMinor, other.borderSeverityMinor, t)!,
      signalSeverityMinor: Color.lerp(signalSeverityMinor, other.signalSeverityMinor, t)!,
      iconSeverityMinor: Color.lerp(iconSeverityMinor, other.iconSeverityMinor, t)!,
      textSeverityMinor: Color.lerp(textSeverityMinor, other.textSeverityMinor, t)!,
      borderSeverityMinorIndicator: Color.lerp(borderSeverityMinorIndicator, other.borderSeverityMinorIndicator, t)!,
      bgSeverityMajor: Color.lerp(bgSeverityMajor, other.bgSeverityMajor, t)!,
      borderSeverityMajor: Color.lerp(borderSeverityMajor, other.borderSeverityMajor, t)!,
      signalSeverityMajor: Color.lerp(signalSeverityMajor, other.signalSeverityMajor, t)!,
      iconSeverityMajor: Color.lerp(iconSeverityMajor, other.iconSeverityMajor, t)!,
      textSeverityMajor: Color.lerp(textSeverityMajor, other.textSeverityMajor, t)!,
      borderSeverityMajorIndicator: Color.lerp(borderSeverityMajorIndicator, other.borderSeverityMajorIndicator, t)!,
      bgSeverityCritical: Color.lerp(bgSeverityCritical, other.bgSeverityCritical, t)!,
      borderSeverityCritical: Color.lerp(borderSeverityCritical, other.borderSeverityCritical, t)!,
      signalSeverityCritical: Color.lerp(signalSeverityCritical, other.signalSeverityCritical, t)!,
      iconSeverityCritical: Color.lerp(iconSeverityCritical, other.iconSeverityCritical, t)!,
      textSeverityCritical: Color.lerp(textSeverityCritical, other.textSeverityCritical, t)!,
      borderSeverityCriticalIndicator: Color.lerp(borderSeverityCriticalIndicator, other.borderSeverityCriticalIndicator, t)!,
      bgRiskLow: Color.lerp(bgRiskLow, other.bgRiskLow, t)!,
      borderRiskLow: Color.lerp(borderRiskLow, other.borderRiskLow, t)!,
      signalRiskLow: Color.lerp(signalRiskLow, other.signalRiskLow, t)!,
      iconRiskLow: Color.lerp(iconRiskLow, other.iconRiskLow, t)!,
      textRiskLow: Color.lerp(textRiskLow, other.textRiskLow, t)!,
      borderRiskLowIndicator: Color.lerp(borderRiskLowIndicator, other.borderRiskLowIndicator, t)!,
      bgRiskMedium: Color.lerp(bgRiskMedium, other.bgRiskMedium, t)!,
      borderRiskMedium: Color.lerp(borderRiskMedium, other.borderRiskMedium, t)!,
      signalRiskMedium: Color.lerp(signalRiskMedium, other.signalRiskMedium, t)!,
      iconRiskMedium: Color.lerp(iconRiskMedium, other.iconRiskMedium, t)!,
      textRiskMedium: Color.lerp(textRiskMedium, other.textRiskMedium, t)!,
      borderRiskMediumIndicator: Color.lerp(borderRiskMediumIndicator, other.borderRiskMediumIndicator, t)!,
      bgRiskHigh: Color.lerp(bgRiskHigh, other.bgRiskHigh, t)!,
      borderRiskHigh: Color.lerp(borderRiskHigh, other.borderRiskHigh, t)!,
      signalRiskHigh: Color.lerp(signalRiskHigh, other.signalRiskHigh, t)!,
      iconRiskHigh: Color.lerp(iconRiskHigh, other.iconRiskHigh, t)!,
      textRiskHigh: Color.lerp(textRiskHigh, other.textRiskHigh, t)!,
      borderRiskHighIndicator: Color.lerp(borderRiskHighIndicator, other.borderRiskHighIndicator, t)!,
      signalStatusUnknown: Color.lerp(signalStatusUnknown, other.signalStatusUnknown, t)!,
      signalStatusHealthy: Color.lerp(signalStatusHealthy, other.signalStatusHealthy, t)!,
      signalStatusWarning: Color.lerp(signalStatusWarning, other.signalStatusWarning, t)!,
      signalStatusMedium: Color.lerp(signalStatusMedium, other.signalStatusMedium, t)!,
      signalStatusUnhealthy: Color.lerp(signalStatusUnhealthy, other.signalStatusUnhealthy, t)!,
      focusRingColor: Color.lerp(focusRingColor, other.focusRingColor, t)!,
    );
  }
}

/// Spacing, icon, control-height, radius and focus scales in logical pixels, plus motion.
abstract final class VelaSizing {
  static const double space5 = 5;
  static const double space10 = 10;
  static const double space15 = 15;
  static const double space20 = 20;
  /// 25 exists; 50 does not. Do not interpolate the scale.
  static const double space25 = 25;
  static const double space30 = 30;
  static const double space40 = 40;
  static const double space60 = 60;
  static const double space80 = 80;
  static const double icon12 = 12;
  /// Button icons never exceed 16. 12 at tiny, 16 everywhere else.
  static const double icon16 = 16;
  static const double icon20 = 20;
  static const double icon24 = 24;
  /// Button and the input family do not share a height ramp.
  static const double controlHeight24 = 24;
  /// Button and the input family do not share a height ramp.
  static const double controlHeight25 = 25;
  /// Button and the input family do not share a height ramp.
  static const double controlHeight26 = 26;
  /// Button and the input family do not share a height ramp.
  static const double controlHeight35 = 35;
  /// Button and the input family do not share a height ramp.
  static const double controlHeight40 = 40;
  /// Button and the input family do not share a height ramp.
  static const double controlHeight48 = 48;
  /// Button and the input family do not share a height ramp.
  static const double controlHeight60 = 60;
  static const double radius3 = 3;
  /// The default corner for every component.
  static const double radius4 = 4;
  static const double radius8 = 8;
  static const double radius12 = 12;
  /// Status Indicator dots and the Toggle track only.
  static const double radiusFull = 9999;
  static const double focusRingWidth = 2;
  static const double focusRingOffset = 2;
  static const Duration durationFast = Duration(milliseconds: 120);
  static const Duration durationBase = Duration(milliseconds: 180);
  static const Cubic easeStandard = Cubic(0.2, 0, 0.2, 1);
}

/// Type ramp. Sizes and line-heights in logical pixels; each composed [TextStyle] sets
/// `height` to line-height ÷ size, which is how Flutter expresses a line-height.
abstract final class VelaTypography {
  static const String fontFamilyPrimary = 'Open Sans';
  static const List<String> fontFamilyPrimaryFallback = <String>['Segoe UI', 'Roboto'];
  static const String fontFamilyDisplay = 'Oswald';
  static const List<String> fontFamilyDisplayFallback = <String>['Open Sans'];
  static const FontWeight fontWeightLight = FontWeight.w300;
  /// Button labels are Regular 400 at every size.
  static const FontWeight fontWeightRegular = FontWeight.w400;
  static const FontWeight fontWeightSemibold = FontWeight.w600;
  static const double textH1Size = 32;
  static const FontWeight textH1Weight = FontWeight.w300;
  static const double textH1LineHeight = 42;
  static const double textH2Size = 24;
  static const FontWeight textH2Weight = FontWeight.w300;
  static const double textH2LineHeight = 33;
  static const double textH3Size = 20;
  static const FontWeight textH3Weight = FontWeight.w300;
  static const double textH3LineHeight = 27;
  static const double textH4Size = 16;
  static const FontWeight textH4Weight = FontWeight.w400;
  static const double textH4LineHeight = 24;
  static const double textH5Size = 14;
  static const FontWeight textH5Weight = FontWeight.w600;
  static const double textH5LineHeight = 21;
  static const double textH6Size = 12;
  static const FontWeight textH6Weight = FontWeight.w600;
  static const double textH6LineHeight = 18;
  static const double textBodySize = 14;
  static const FontWeight textBodyWeight = FontWeight.w400;
  static const double textBodyLineHeight = 21;
  static const double textMetaSize = 12;
  static const FontWeight textMetaWeight = FontWeight.w400;
  static const double textMetaLineHeight = 18;
  static const double textMetaTracking = 0.3;
  static const double textButtonTinySize = 12;
  static const double textButtonTinyLineHeight = 18;
  static const double textButtonRegularSize = 14;
  static const double textButtonRegularLineHeight = 21;
  static const double textButtonLargeSize = 15;
  static const double textButtonLargeLineHeight = 22;
  static const double textButtonHugeSize = 16;
  static const double textButtonHugeLineHeight = 24;
  static const double textTabSize = 14;
  static const double textTabLineHeight = 19;
  static const double textTabLargeSize = 18;
  static const double textTabLargeLineHeight = 25;

  // Composed styles — one per size in the ramp. All use fontFamilyPrimary; fontFamilyDisplay
  // (Oswald) is for large stat displays only and has no text style of its own, as in the CSS.
  static const TextStyle h1 = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textH1Size,
    fontWeight: textH1Weight,
    height: textH1LineHeight / textH1Size,
  );
  static const TextStyle h2 = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textH2Size,
    fontWeight: textH2Weight,
    height: textH2LineHeight / textH2Size,
  );
  static const TextStyle h3 = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textH3Size,
    fontWeight: textH3Weight,
    height: textH3LineHeight / textH3Size,
  );
  static const TextStyle h4 = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textH4Size,
    fontWeight: textH4Weight,
    height: textH4LineHeight / textH4Size,
  );
  static const TextStyle h5 = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textH5Size,
    fontWeight: textH5Weight,
    height: textH5LineHeight / textH5Size,
  );
  static const TextStyle h6 = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textH6Size,
    fontWeight: textH6Weight,
    height: textH6LineHeight / textH6Size,
  );
  static const TextStyle body = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textBodySize,
    fontWeight: textBodyWeight,
    height: textBodyLineHeight / textBodySize,
  );
  static const TextStyle meta = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textMetaSize,
    fontWeight: textMetaWeight,
    height: textMetaLineHeight / textMetaSize,
    letterSpacing: textMetaTracking,
  );
  static const TextStyle buttonTiny = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textButtonTinySize,
    fontWeight: fontWeightRegular,
    height: textButtonTinyLineHeight / textButtonTinySize,
  );
  static const TextStyle buttonRegular = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textButtonRegularSize,
    fontWeight: fontWeightRegular,
    height: textButtonRegularLineHeight / textButtonRegularSize,
  );
  static const TextStyle buttonLarge = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textButtonLargeSize,
    fontWeight: fontWeightRegular,
    height: textButtonLargeLineHeight / textButtonLargeSize,
  );
  static const TextStyle buttonHuge = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textButtonHugeSize,
    fontWeight: fontWeightRegular,
    height: textButtonHugeLineHeight / textButtonHugeSize,
  );
  static const TextStyle tab = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textTabSize,
    fontWeight: fontWeightRegular,
    height: textTabLineHeight / textTabSize,
  );
  static const TextStyle tabLarge = TextStyle(
    fontFamily: fontFamilyPrimary,
    fontFamilyFallback: fontFamilyPrimaryFallback,
    fontSize: textTabLargeSize,
    fontWeight: fontWeightRegular,
    height: textTabLargeLineHeight / textTabLargeSize,
  );
}

/// A [ThemeData] seeded from the semantic tokens.
///
/// The [ColorScheme] mapping is a starting point — Material's colour roles and Vela's
/// semantics are different vocabularies. The full palette is always available through
/// [VelaColors], which this installs as a theme extension.
ThemeData velaThemeData(Brightness brightness) {
  final VelaColors c = brightness == Brightness.dark ? VelaColors.dark : VelaColors.light;
  return ThemeData(
    useMaterial3: true,
    brightness: brightness,
    colorScheme: ColorScheme(
      brightness: brightness,
      primary: c.btnPrimaryBg,
      onPrimary: c.btnPrimaryText,
      secondary: c.primaryTint,
      onSecondary: c.textOnTint,
      error: c.textError,
      onError: c.textOnBrand,
      surface: c.bgGlobal,
      onSurface: c.textDefault,
    ),
    scaffoldBackgroundColor: c.bgGlobal,
    canvasColor: c.bgGlobal,
    cardColor: c.bgRaised,
    dividerColor: c.borderSubtle,
    focusColor: c.focusRingColor,
    hoverColor: c.bgHover,
    disabledColor: c.textInactive,
    fontFamily: VelaTypography.fontFamilyPrimary,
    textTheme: const TextTheme(
      headlineLarge: VelaTypography.h1,
      headlineMedium: VelaTypography.h2,
      headlineSmall: VelaTypography.h3,
      titleLarge: VelaTypography.h4,
      titleMedium: VelaTypography.h5,
      titleSmall: VelaTypography.h6,
      bodyMedium: VelaTypography.body,
      labelSmall: VelaTypography.meta,
      labelLarge: VelaTypography.buttonRegular,
    ),
    extensions: <ThemeExtension<dynamic>>[c],
  );
}
