/**
 * Figma drift check — the read-back half of the token loop.
 *
 * tokens:figma pushes the JSON into Figma. Nothing stopped someone editing a
 * variable in the Figma UI afterwards, and nothing would have noticed. This
 * closes that: it reads every variable back out of the library and diffs the
 * resolved values against tokens/vela.tokens.json.
 *
 * Two steps, because Figma's REST API only lets Enterprise plans READ variables
 * too — so the read runs inside the file, like the write:
 *
 *   npm run tokens:figma:read > /tmp/read.js     # run the printed script in the
 *                                                # file (MCP / Scripter), save the
 *                                                # returned JSON as /tmp/figma.json
 *   npm run tokens:figma:check -- /tmp/figma.tsv
 *
 * Exit 1 on any mismatch, so it can gate a Figma library publish the way
 * `verify` gates an npm publish.
 */
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const doc = JSON.parse(readFileSync(join(root, 'tokens/vela.tokens.json'), 'utf8'))

// ---------- what the JSON says the library should contain ----------
const all = {}
for (const [group, tokens] of Object.entries(doc)) {
  if (group.startsWith('$')) continue
  for (const [name, t] of Object.entries(tokens)) all[name] = { ...t, group }
}
const collectionOf = { primitives: 'Primitives', color: 'Color', sizing: 'Sizing', typography: 'Typography' }

const resolveColor = (name, mode, seen = new Set()) => {
  const t = all[name]
  if (!t) throw new Error('unknown token ' + name)
  let v = t.$value
  if (mode === 'dark' && t.$extensions?.vela?.dark) v = t.$extensions.vela.dark
  if (typeof v === 'string' && /^\{.+\}$/.test(v)) {
    const target = v.slice(1, -1)
    if (seen.has(target)) throw new Error('alias cycle at ' + name)
    seen.add(target)
    return resolveColor(target, mode, seen)
  }
  return v
}

const expected = {}
for (const [name, t] of Object.entries(all)) {
  const figma = t.$extensions?.vela?.figma
  if (!figma) continue
  const key = collectionOf[t.group] + '|' + figma
  if (t.$type === 'color') expected[key] = { css: name, light: resolveColor(name, 'light'), dark: resolveColor(name, 'dark') }
  else if (t.$type === 'dimension') expected[key] = { css: name, value: t.$value.value }
  else if (t.$type === 'number') expected[key] = { css: name, value: t.$value }
}

// ---------- mode 1: print the read script ----------
if (process.argv[2] === '--read' || !process.argv[2]) {
  process.stdout.write(`// Generated by scripts/figma-drift.mjs — reads every variable back, resolved per mode. Do not edit.
const colls = await figma.variables.getLocalVariableCollectionsAsync();
const cById = Object.fromEntries(colls.map(c => [c.id, c]));
const vars = await figma.variables.getLocalVariablesAsync();
const vById = Object.fromEntries(vars.map(v => [v.id, v]));
const hex = c => '#' + [c.r, c.g, c.b].map(x => Math.round(x * 255).toString(16).padStart(2, '0')).join('');
// follow aliases; when an alias crosses into a collection with different modes, match by mode NAME, else first mode
const resolve = (v, modeName) => {
  let cur = v;
  for (let i = 0; i < 12; i++) {
    const c = cById[cur.variableCollectionId];
    const m = c.modes.find(x => x.name === modeName) || c.modes[0];
    const val = cur.valuesByMode[m.modeId];
    if (val && typeof val === 'object' && val.type === 'VARIABLE_ALIAS') { cur = vById[val.id]; continue; }
    return val;
  }
  throw new Error('alias chain too deep at ' + v.name);
};
const lines = [];
for (const v of vars) {
  const c = cById[v.variableCollectionId];
  const key = c.name + '|' + v.name;
  const css = ((v.codeSyntax && v.codeSyntax.WEB) || '').replace(/^var\\(--vela-/, '').replace(/\\)$/, '');
  if (v.resolvedType === 'COLOR') lines.push([key, css, hex(resolve(v, 'Light')), hex(resolve(v, 'Dark'))].join('\\t'));
  else if (v.resolvedType === 'FLOAT') lines.push([key, css, resolve(v, 'Value')].join('\\t'));
}
return lines.join('\\n');
`)
  process.exit(0)
}

// ---------- mode 2: compare a saved read result ----------
// the read script returns one line per variable: key \t css \t light \t dark   (or key \t css \t value)
const actual = {}
for (const line of readFileSync(process.argv[2], 'utf8').split('\n')) {
  if (!line.trim()) continue
  const [key, css, a, b] = line.split('\t')
  actual[key] = b !== undefined ? { css, light: a, dark: b } : { css, value: Number(a) }
}
const problems = []
for (const [key, e] of Object.entries(expected)) {
  const a = actual[key]
  if (!a) { problems.push(`MISSING in Figma   ${key}`); continue }
  if ('value' in e) {
    if (Math.abs(a.value - e.value) > 0.001) problems.push(`VALUE   ${key}: figma=${a.value} json=${e.value}`)
  } else {
    if (a.light !== e.light) problems.push(`LIGHT   ${key}: figma=${a.light} json=${e.light}`)
    if (a.dark !== e.dark) problems.push(`DARK    ${key}: figma=${a.dark} json=${e.dark}`)
  }
  if (a.css !== e.css) problems.push(`SYNTAX  ${key}: figma="${a.css}" json="${e.css}"`)
}
for (const key of Object.keys(actual)) if (!expected[key]) problems.push(`EXTRA in Figma     ${key} (no token in JSON)`)

console.log(`\n  FIGMA ↔ JSON   ${Object.keys(expected).length} tokens expected · ${Object.keys(actual).length} variables read\n`)
if (problems.length === 0) console.log('  No drift. The library matches tokens/vela.tokens.json exactly.\n')
else { for (const p of problems) console.log('  ' + p); console.log(`\n  ${problems.length} problem(s). Fix in the JSON and re-run tokens:figma — never in Figma alone.\n`) }
process.exit(problems.length ? 1 : 0)
