/**
 * Figma sync — the other half of "one edit, both targets".
 *
 * Figma's REST API only lets Enterprise plans WRITE variables, so this does not
 * call the REST API. Instead it compiles tokens/vela.tokens.json into a Plugin
 * API script and prints it. Run that script inside the Vela Design System file
 * (via the Figma MCP `use_figma` tool, or the Scripter plugin) and every
 * variable is created-or-updated in place: value per mode, alias per mode,
 * scopes, description, and the `var(--vela-*)` code syntax. A variable whose
 * Figma type changed is removed and recreated under the same name, because a
 * resolved type cannot be edited.
 *
 *   npm run tokens:figma            # prints the script to stdout
 *   npm run tokens:figma > /tmp/sync.js
 *
 * Idempotent: it looks variables up by collection + name and updates them, so
 * re-running never duplicates. The mapping from token name → Figma name lives
 * in each token's $extensions.vela.figma, extracted from the live file, so the
 * names here match the library exactly.
 */
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const doc = JSON.parse(readFileSync(join(root, 'tokens/vela.tokens.json'), 'utf8'))

const SCOPES = {
  primitive: [],
  surface: ['FRAME_FILL', 'SHAPE_FILL'], bg: ['FRAME_FILL', 'SHAPE_FILL'], signal: ['FRAME_FILL', 'SHAPE_FILL'],
  border: ['STROKE_COLOR'], indicator: ['STROKE_COLOR'], text: ['TEXT_FILL'],
  icon: ['SHAPE_FILL', 'STROKE_COLOR'],
  space: ['WIDTH_HEIGHT', 'GAP'], 'control-height': ['WIDTH_HEIGHT'], iconSize: ['WIDTH_HEIGHT'],
  radius: ['CORNER_RADIUS'], size: ['FONT_SIZE'], 'line-height': ['LINE_HEIGHT'], weight: ['FONT_WEIGHT'],
}
const scopesFor = (group, figmaName, cssName) => {
  if (group === 'primitives') return SCOPES.primitive
  const head = figmaName.split('/')[0], last = figmaName.split('/').pop()
  if (group === 'color') {
    if (/^(severity|risk)$/.test(head)) return SCOPES[last] ?? SCOPES.bg
    if (head === 'status') return SCOPES.signal
    if (head === 'focus') return SCOPES.border
    if (head === 'button' || head === 'control') {
      if (/text|placeholder/.test(cssName)) return SCOPES.text
      if (/border/.test(cssName)) return SCOPES.border
      return SCOPES.bg
    }
    return SCOPES[head] ?? SCOPES.bg
  }
  if (group === 'sizing') return head === 'icon' ? SCOPES.iconSize : (SCOPES[head] ?? ['WIDTH_HEIGHT'])
  // TIMING and EASING variables have no scopes — setting any throws — the type decides where Figma offers them
  if (group === 'motion') return null
  return SCOPES[head] ?? []
}

const collectionOf = { primitives: 'Primitives', color: 'Color', sizing: 'Sizing', typography: 'Typography', motion: 'Motion' }
// `--only <Collection>` limits the printed script to one collection (the MCP script cap is 50 KB).
const only = process.argv.includes('--only') ? process.argv[process.argv.indexOf('--only') + 1] : null
const entries = []
for (const [group, tokens] of Object.entries(doc)) {
  if (group.startsWith('$')) continue
  for (const [css, t] of Object.entries(tokens)) {
    const figma = t.$extensions?.vela?.figma
    if (!figma) continue
    // Colours become COLOR variables and numbers FLOAT. The motion tokens use Figma's own motion
    // types (Figma Motion, June 2026): a duration is a TIMING variable — Figma keeps timing in
    // seconds, so 120ms is stored as 0.12 — and the curve an EASING variable holding the bezier.
    // A Figma Motion timeline can bind them; a prototype transition still cannot (foundations/motion.md).
    if (t.$type === 'fontFamily') continue
    if (only && collectionOf[group] !== only) continue
    const type = t.$type === 'color' ? 'COLOR' : t.$type === 'duration' ? 'TIMING' : t.$type === 'cubicBezier' ? 'EASING' : 'FLOAT'
    const value = (v) =>
      t.$type === 'dimension' ? v.value
      : t.$type === 'duration' ? Number(String(v).replace(/ms$/, '')) / 1000
      : t.$type === 'cubicBezier' ? { type: 'CUSTOM_CUBIC_BEZIER', easingFunctionCubicBezier: { x1: v[0], y1: v[1], x2: v[2], y2: v[3] } }
      : v
    entries.push({
      collection: collectionOf[group], name: figma, css,
      type,
      light: value(t.$value),
      dark: t.$type === 'color' ? (t.$extensions?.vela?.dark ?? t.$value) : undefined,
      scopes: scopesFor(group, figma, css),
      description: t.$description ?? '',
    })
  }
}

// `{name}` aliases refer to other tokens by CSS name → resolve to Figma names.
const figmaNameOf = Object.fromEntries(entries.map((e) => [e.css, e.name]))
const collOf = Object.fromEntries(entries.map((e) => [e.css, e.collection]))
for (const e of entries) {
  for (const k of ['light', 'dark']) {
    const v = e[k]
    if (typeof v === 'string' && /^\{.+\}$/.test(v)) {
      const target = v.slice(1, -1)
      e[k] = { alias: figmaNameOf[target], collection: collOf[target] }
    }
  }
}

const script = `// Generated by scripts/sync-figma.mjs from tokens/vela.tokens.json — do not edit.
const ENTRIES = ${JSON.stringify(entries)};
const colls = await figma.variables.getLocalVariableCollectionsAsync();
const byName = Object.fromEntries(colls.map(c => [c.name, c]));
for (const n of ['Primitives','Color','Sizing','Typography','Motion']) {
  if (!byName[n]) { const c = figma.variables.createVariableCollection(n); c.renameMode(c.modes[0].modeId, n === 'Color' ? 'Light' : 'Value'); if (n === 'Color') c.addMode('Dark'); byName[n] = c; }
}
const mode = (c, m) => c.modes.find(x => x.name === m).modeId;
const all = await figma.variables.getLocalVariablesAsync();
const lookup = {};
for (const v of all) lookup[v.variableCollectionId + '|' + v.name] = v;
const hex = h => { const n = parseInt(h.slice(1), 16); return { r: ((n>>16)&255)/255, g: ((n>>8)&255)/255, b: (n&255)/255 }; };
// an alias → VARIABLE_ALIAS; a hex string → RGB; TIMING seconds and the EASING object pass through as they are
const val = (x, type) => (x && typeof x === 'object' && x.alias) ? { type: 'VARIABLE_ALIAS', id: lookup[byName[x.collection].id + '|' + x.alias].id } : (type === 'COLOR' && typeof x === 'string' ? hex(x) : x);
let created = 0, updated = 0, retyped = 0;
// two passes so aliases always resolve: primitives first, then everything else
for (const pass of [e => e.collection === 'Primitives', e => e.collection !== 'Primitives']) {
  for (const e of ENTRIES.filter(pass)) {
    const c = byName[e.collection]; const key = c.id + '|' + e.name;
    let v = lookup[key];
    // a resolved type cannot be edited: a token whose Figma type changed is removed and recreated under its name
    if (v && v.resolvedType !== e.type) { v.remove(); v = null; retyped++; }
    if (!v) { v = figma.variables.createVariable(e.name, c, e.type); lookup[key] = v; created++; } else updated++;
    if (e.collection === 'Color') { v.setValueForMode(mode(c,'Light'), val(e.light, e.type)); v.setValueForMode(mode(c,'Dark'), val(e.dark, e.type)); }
    else v.setValueForMode(c.modes[0].modeId, val(e.light, e.type));
    if (e.scopes) v.scopes = e.scopes; v.description = e.description;
    v.setVariableCodeSyntax('WEB', 'var(--vela-' + e.css + ')');
  }
}
return { created, updated, retyped, total: ENTRIES.length };
`
process.stdout.write(script)
